"use client";
import Image from "next/image";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, Award, Calendar, ExternalLink, Flame, RotateCcw, Target, Trophy } from "lucide-react";
import type { UserAnalysis } from "@/types/codeforces";
import { ActivityCalendar } from "@/components/activity-calendar";
import { DifficultyChart, RatingChart, TagsChart } from "@/components/charts";
import { Badge, Card, CardHeader, Empty, Metric } from "@/components/ui";
import { formatRelativeTime, rankColor } from "@/lib/utils";

function Loading() { return <main className="mx-auto max-w-7xl px-5 py-8"><div className="mb-6 h-28 rounded-2xl skeleton"/><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-24 rounded-2xl skeleton"/>)}</div><div className="mt-3 grid gap-3 lg:grid-cols-3"><div className="h-96 rounded-2xl skeleton lg:col-span-2"/><div className="h-96 rounded-2xl skeleton"/></div></main> }

export default function DashboardPage() {
  const { handle } = useParams<{handle:string}>(); const [data,setData]=useState<UserAnalysis>(); const [error,setError]=useState("");
  useEffect(()=>{fetch(`/api/analysis/${encodeURIComponent(handle)}`).then(async r=>{const json=await r.json();if(!r.ok)throw new Error(json.error);setData(json)}).catch(e=>setError(e.message))},[handle]);
  if(error) return <main className="mx-auto max-w-xl px-5 py-32 text-center"><div className="mx-auto grid size-12 place-items-center rounded-full bg-red-500/10 text-red-400"><RotateCcw/></div><h1 className="mt-5 text-2xl font-semibold">Analysis interrupted</h1><p className="mt-3 text-sm text-zinc-500">{error}</p><Link href="/" className="mt-6 inline-block rounded-lg bg-white px-4 py-2 text-sm font-medium text-black">Try another handle</Link></main>;
  if(!data) return <Loading/>;
  const p=data.profile; const weak=[...data.tagStats].filter(t=>t.wrongAttempts>=2).sort((a,b)=>b.weakness-a.weakness).slice(0,4);
  return <main className="mx-auto max-w-7xl px-5 py-7 fade-up"><div className="mb-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div className="flex items-center gap-4"><Image src={p.titlePhoto.replace("http://","https://")} alt={p.handle} width={64} height={64} unoptimized className="size-16 rounded-xl border border-white/10 object-cover"/><div><div className="flex items-center gap-2"><h1 className={`text-2xl font-semibold ${rankColor(p.rank)}`}>{p.handle}</h1><a href={`https://codeforces.com/profile/${p.handle}`} target="_blank" rel="noreferrer" className="text-zinc-600 hover:text-white"><ExternalLink size={14}/></a></div><p className="mt-1 text-sm capitalize text-zinc-500">{p.rank ?? "unrated"}{p.organization ? ` · ${p.organization}`:""}</p><p className="mt-1 text-xs text-zinc-600">Last online {formatRelativeTime(p.lastOnlineTimeSeconds)}</p></div></div><div className="flex gap-2"><Link href={`/upsolve/${p.handle}`} className="rounded-lg border border-white/10 px-3 py-2 text-xs hover:bg-white/5">Upsolve queue</Link><Link href={`/compare?a=${p.handle}`} className="rounded-lg bg-[#b7f34a] px-3 py-2 text-xs font-semibold text-black">Compare</Link></div></div>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Current rating" value={p.rating ?? "—"} detail={`Peak ${p.maxRating ?? "unrated"}`} icon={Trophy}/><Metric label="Unique solved" value={data.solvedCount.toLocaleString()} detail={`${data.averageDifficulty || "—"} average difficulty`} icon={Target}/><Metric label="Rated contests" value={data.ratingStats.totalContests} detail={data.ratingStats.bestRank ? `Best rank #${data.ratingStats.bestRank}`:"No rated contests"} icon={Award}/><Metric label="Current streak" value={`${data.currentStreak}d`} detail={`${data.activeDays30} active days this month`} icon={Flame}/></div>
  <div className="mt-3 grid gap-3 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader title="Rating trajectory" eyebrow="Contest history" action={<div className="flex gap-3 text-[11px]"><span className="flex items-center gap-1 text-emerald-400"><ArrowUp size={12}/>+{data.ratingStats.biggestGain}</span><span className="flex items-center gap-1 text-red-400"><ArrowDown size={12}/>{data.ratingStats.biggestLoss}</span></div>}/><div className="px-1 pb-3 pt-2">{data.ratings.length?<RatingChart data={data.ratings}/>:<Empty>No rated contest history yet.</Empty>}</div></Card><Card><CardHeader title="Practice signal" eyebrow="Recommended next"/><div className="p-5"><div className="rounded-xl border border-[#b7f34a]/15 bg-[#b7f34a]/5 p-4"><p className="text-xs text-zinc-500">Difficulty range</p><p className="mt-1 text-2xl font-semibold text-[#b7f34a]">{data.practiceRange[0]}–{data.practiceRange[1]}</p></div><div className="mt-4 space-y-3">{data.recommendations.map((r,i)=><div className="flex gap-3 text-sm leading-5 text-zinc-400" key={r}><span className="mt-0.5 text-xs font-semibold text-[#b7f34a]">0{i+1}</span>{r}</div>)}</div></div></Card></div>
  <div className="mt-3 grid gap-3 lg:grid-cols-2"><Card><CardHeader title="Solved by difficulty" eyebrow="Depth"/><div className="px-2 pb-3"><DifficultyChart data={data.ratingBuckets}/></div></Card><Card><CardHeader title="Topics in your submissions" eyebrow="Breadth" action={<span className="text-[10px] text-zinc-600">solved / attempts</span>}/><div className="px-2 pb-3"><TagsChart data={data.tagStats}/></div></Card></div>
  <div className="mt-3 grid gap-3 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader title="Solving rhythm" eyebrow="Last 6 months" action={<span className="text-xs text-zinc-500">Longest streak {data.longestStreak}d</span>}/><ActivityCalendar days={data.activity}/></Card><Card><CardHeader title="Weak-topic watchlist" eyebrow="High friction"/><div className="divide-y divide-white/7 px-5 pb-2">{weak.length?weak.map(t=><div className="flex items-center justify-between py-3" key={t.tag}><div><p className="text-sm capitalize">{t.tag}</p><p className="mt-1 text-[10px] text-zinc-600">{t.solved} solved · {t.wrongAttempts} wrong attempts</p></div><Badge tone={t.accuracy<35?"red":"default"}>{t.accuracy}% accuracy</Badge></div>):<Empty>Not enough wrong attempts to find a weak topic.</Empty>}</div></Card></div>
  <div className="mt-3 grid gap-3 lg:grid-cols-5"><Card className="lg:col-span-3"><CardHeader title="Recent submissions" eyebrow="Latest activity"/><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-zinc-600"><tr><th className="px-5 py-3 font-medium">Problem</th><th className="px-3 py-3 font-medium">Difficulty</th><th className="px-3 py-3 font-medium">Verdict</th><th className="px-5 py-3 text-right font-medium">When</th></tr></thead><tbody>{data.submissions.slice(0,8).map(s=><tr className="border-t border-white/6" key={s.id}><td className="max-w-56 truncate px-5 py-3 text-zinc-300">{s.problem.index}. {s.problem.name}</td><td className="px-3 py-3 text-zinc-500">{s.problem.rating??"—"}</td><td className="px-3 py-3"><Badge tone={s.verdict==="OK"?"green":"red"}>{s.verdict==="OK"?"Accepted":s.verdict?.replaceAll("_"," ")??"Testing"}</Badge></td><td className="whitespace-nowrap px-5 py-3 text-right text-zinc-600">{formatRelativeTime(s.creationTimeSeconds)}</td></tr>)}</tbody></table></div></Card><Card className="lg:col-span-2"><CardHeader title="Contest history" eyebrow="Recent rated rounds"/><div className="divide-y divide-white/7 px-5">{data.ratings.slice(-7).reverse().map(r=>{const change=r.newRating-r.oldRating;return <div key={r.contestId} className="flex items-center gap-3 py-3"><Calendar size={14} className="shrink-0 text-zinc-600"/><div className="min-w-0 flex-1"><p className="truncate text-xs text-zinc-300">{r.contestName}</p><p className="mt-1 text-[10px] text-zinc-600">Rank #{r.rank} · {r.newRating}</p></div><span className={`text-xs ${change>=0?"text-emerald-400":"text-red-400"}`}>{change>=0?"+":""}{change}</span></div>})}</div></Card></div></main>;
}
