"use client";
import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, GitCompareArrows, LoaderCircle } from "lucide-react";
import type { UserAnalysis } from "@/types/codeforces";
import { ComparisonChart } from "@/components/charts";
import { Card, CardHeader } from "@/components/ui";
import { rankColor } from "@/lib/utils";

export default function ComparePage() {
  const [a,setA]=useState(""); const [b,setB]=useState(""); const [users,setUsers]=useState<[UserAnalysis,UserAnalysis]>(); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  async function compare(e?:FormEvent){e?.preventDefault();if(!a.trim()||!b.trim()){setError("Enter both handles.");return}setLoading(true);setError("");try{const responses=await Promise.all([a,b].map(h=>fetch(`/api/analysis/${encodeURIComponent(h.trim())}`)));const json=await Promise.all(responses.map(r=>r.json()));const failed=responses.findIndex(r=>!r.ok);if(failed>=0)throw new Error(json[failed].error);setUsers(json as [UserAnalysis,UserAnalysis])}catch(e){setError(e instanceof Error?e.message:"Comparison failed.")}finally{setLoading(false)}}
  useEffect(()=>{const prefilled=new URLSearchParams(window.location.search).get("a");if(prefilled)queueMicrotask(()=>setA(prefilled))},[]);
  const rows=users?[{label:"Current rating",a:users[0].profile.rating??"—",b:users[1].profile.rating??"—"},{label:"Peak rating",a:users[0].profile.maxRating??"—",b:users[1].profile.maxRating??"—"},{label:"Unique solved",a:users[0].solvedCount,b:users[1].solvedCount},{label:"Rated contests",a:users[0].ratings.length,b:users[1].ratings.length},{label:"Average difficulty",a:users[0].averageDifficulty||"—",b:users[1].averageDifficulty||"—"},{label:"Best rank",a:users[0].ratingStats.bestRank?`#${users[0].ratingStats.bestRank}`:"—",b:users[1].ratingStats.bestRank?`#${users[1].ratingStats.bestRank}`:"—"},{label:"Strongest topic",a:users[0].tagStats[0]?.tag??"—",b:users[1].tagStats[0]?.tag??"—"}]:[];
  return <main className="mx-auto min-h-[80vh] max-w-6xl px-5 py-16"><div className="mx-auto max-w-2xl text-center"><div className="mx-auto grid size-10 place-items-center rounded-xl bg-[#b7f34a]/10 text-[#b7f34a]"><GitCompareArrows size={20}/></div><h1 className="mt-5 text-4xl font-semibold tracking-[-.04em]">Compare the work,<br/>not just the rating.</h1><p className="mt-4 text-sm leading-6 text-zinc-500">Put two Codeforces histories side by side and see how their depth, activity, and contest trajectories differ.</p></div><form onSubmit={compare} className="mx-auto mt-9 grid max-w-3xl gap-2 sm:grid-cols-[1fr_auto_1fr_auto]"><input aria-label="First handle" value={a} onChange={e=>setA(e.target.value)} placeholder="First handle" className="rounded-xl border border-white/10 bg-[#11141a] px-4 py-3 text-sm outline-none focus:border-[#b7f34a]/50"/><span className="hidden self-center text-xs text-zinc-600 sm:block">VS</span><input aria-label="Second handle" value={b} onChange={e=>setB(e.target.value)} placeholder="Second handle" className="rounded-xl border border-white/10 bg-[#11141a] px-4 py-3 text-sm outline-none focus:border-[#b7f34a]/50"/><button disabled={loading} className="flex items-center justify-center gap-2 rounded-xl bg-[#b7f34a] px-5 py-3 text-sm font-semibold text-black">{loading?<LoaderCircle size={16} className="animate-spin"/>:<><span>Compare</span><ArrowRight size={15}/></>}</button></form>{error&&<p className="mt-3 text-center text-xs text-red-400">{error}</p>}
  {users?<div className="mt-10 fade-up"><div className="grid grid-cols-[1fr_1fr_1fr] border-y border-white/8 py-5 text-center"><div/><div><p className={`text-xl font-semibold ${rankColor(users[0].profile.rank)}`}>{users[0].profile.handle}</p><p className="mt-1 text-xs capitalize text-zinc-600">{users[0].profile.rank??"unrated"}</p></div><div><p className={`text-xl font-semibold ${rankColor(users[1].profile.rank)}`}>{users[1].profile.handle}</p><p className="mt-1 text-xs capitalize text-zinc-600">{users[1].profile.rank??"unrated"}</p></div></div><Card className="mt-3 overflow-hidden"><div className="divide-y divide-white/7">{rows.map(row=><div key={row.label} className="grid grid-cols-3 items-center px-5 py-4 text-center text-sm"><p className="text-left text-xs text-zinc-500">{row.label}</p><p className="font-medium capitalize">{row.a}</p><p className="font-medium capitalize">{row.b}</p></div>)}</div></Card><Card className="mt-3"><CardHeader title="Rating trajectory by contest" eyebrow="Career comparison"/><div className="px-2 pb-4"><ComparisonChart a={users[0].ratings} b={users[1].ratings} names={[users[0].profile.handle,users[1].profile.handle]}/></div></Card></div>:<div className="mx-auto mt-20 max-w-lg text-center text-sm text-zinc-600"><p>Your comparison will appear here.</p><p className="mt-2 text-xs">Tip: rating is a snapshot. Solved depth and contest frequency usually tell the better story.</p></div>}</main>;
}
