import Link from "next/link";
import { ArrowUpRight, BarChart3, CalendarDays, Check, GitCompareArrows, Radar, Target } from "lucide-react";
import { HandleSearch } from "@/components/handle-search";

const features = [
  { icon: BarChart3, title: "Read the trend", copy: "See rating movement, contest swings, consistency, and the moments where your practice paid off." },
  { icon: Radar, title: "Find the weak links", copy: "Turn submission history into topic accuracy and a clear list of skills worth practicing next." },
  { icon: Target, title: "Upsolve with intent", copy: "Recover attempted problems, rank them by relevance, and keep a lightweight practice queue." },
  { icon: GitCompareArrows, title: "Compare trajectories", copy: "Compare two handles beyond rating—with solved depth, contest history, and topic strengths." },
  { icon: CalendarDays, title: "Stay in rhythm", copy: "Track active days, solving streaks, and upcoming contests without the spreadsheet archaeology." },
];

export default function Home() {
  return <main><section className="grid-glow relative overflow-hidden border-b border-white/7"><div className="mx-auto flex min-h-[720px] max-w-7xl flex-col items-center justify-center px-5 py-24 text-center"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#b7f34a]/20 bg-[#b7f34a]/7 px-3 py-1.5 text-xs text-[#c5ff68]"><span className="size-1.5 rounded-full bg-[#b7f34a] shadow-[0_0_10px_#b7f34a]"/>Your Codeforces history, made useful</div><h1 className="max-w-4xl text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-7xl md:text-[92px]">Know what to<br/><span className="text-[#b7f34a]">solve next.</span></h1><p className="mt-7 max-w-2xl text-base leading-7 text-zinc-400 sm:text-lg">CPulse turns your contests and submissions into a focused practice plan—so every wrong answer has somewhere useful to go.</p><div id="analyze" className="mt-9 flex w-full justify-center scroll-mt-28"><HandleSearch /></div><p className="mt-3 text-xs text-zinc-600">No account. No setup. Just your public Codeforces handle.</p><div className="mt-16 grid w-full max-w-4xl grid-cols-3 gap-px overflow-hidden rounded-xl border border-white/8 bg-white/8 text-left"><div className="bg-[#0c0f13] p-5"><p className="text-2xl font-semibold text-[#b7f34a]">01</p><p className="mt-1 text-xs text-zinc-500">Enter a handle</p></div><div className="bg-[#0c0f13] p-5"><p className="text-2xl font-semibold text-[#b7f34a]">02</p><p className="mt-1 text-xs text-zinc-500">Read the signal</p></div><div className="bg-[#0c0f13] p-5"><p className="text-2xl font-semibold text-[#b7f34a]">03</p><p className="mt-1 text-xs text-zinc-500">Practice smarter</p></div></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-24"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#b7f34a]">One honest dashboard</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Less noise.<br/>More next moves.</h2><p className="mt-5 max-w-md text-sm leading-6 text-zinc-500">A profile tells you where you are. CPulse is built to tell you why—and where a little focused work can change the curve.</p><Link href="/compare" className="mt-7 inline-flex items-center gap-2 text-sm text-zinc-200 hover:text-[#b7f34a]">Compare two handles <ArrowUpRight size={15}/></Link></div><div className="grid gap-3 sm:grid-cols-2">{features.map(({icon: Icon, title, copy}, index) => <article key={title} className={`card p-5 transition hover:-translate-y-0.5 hover:border-white/20 ${index === 4 ? "sm:col-span-2" : ""}`}><Icon size={20} className="text-[#b7f34a]"/><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">{copy}</p></article>)}</div></div></section>
  <section className="border-y border-white/7 bg-[#0b0e12]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-2 lg:items-center"><div className="card overflow-hidden p-2"><div className="rounded-xl border border-white/8 bg-[#090b0e] p-5"><div className="flex items-center justify-between border-b border-white/8 pb-4"><div><p className="text-xs text-zinc-500">Practice signal</p><p className="mt-1 text-xl font-semibold">The next 200 points</p></div><span className="rounded-lg bg-[#b7f34a]/10 px-3 py-2 text-xs text-[#b7f34a]">1300–1500</span></div>{["Dynamic programming", "Binary search", "Graphs"].map((tag, i) => <div key={tag} className="flex items-center gap-3 border-b border-white/6 py-4 last:border-0"><span className="grid size-7 place-items-center rounded-md bg-white/5 text-xs text-zinc-500">{i + 1}</span><div className="flex-1"><p className="text-sm">{tag}</p><div className="mt-2 h-1 rounded bg-white/5"><div className="h-1 rounded bg-[#b7f34a]" style={{width: `${72 - i * 14}%`}}/></div></div><Check size={14} className="text-zinc-600"/></div>)}</div></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#b7f34a]">From history to direction</p><h2 className="mt-3 max-w-lg text-4xl font-semibold tracking-[-.04em]">Your wrong answers are data, not debris.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-zinc-400">CPulse connects mistakes to topics, topics to difficulty, and difficulty to a practical range. The result is a plan you can actually use in the next session.</p></div></div></section>
  <section className="mx-auto max-w-5xl px-5 py-28 text-center"><h2 className="text-4xl font-semibold tracking-[-.04em]">Ready to read your curve?</h2><p className="mt-4 text-zinc-500">One handle. About ten seconds. A much clearer practice session.</p><div className="mt-7 flex justify-center"><HandleSearch compact/></div></section></main>;
}
