"use client";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { ExternalLink, LoaderCircle, Target } from "lucide-react";
import type { UpsolveProblem, UserAnalysis } from "@/types/codeforces";
import { Badge, Card, Empty } from "@/components/ui";
import { formatRelativeTime } from "@/lib/utils";

type Status="planned"|"solved"|"skipped";
export default function UpsolvePage(){const {handle}=useParams<{handle:string}>();const [items,setItems]=useState<UpsolveProblem[]>([]);const [statuses,setStatuses]=useState<Record<string,Status>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [filter,setFilter]=useState<Status|"all">("planned");
  useEffect(()=>{const key=`cpulse-upsolve-${handle.toLowerCase()}`;try{const stored=JSON.parse(localStorage.getItem(key)??"{}");queueMicrotask(()=>setStatuses(stored))}catch{};fetch(`/api/analysis/${encodeURIComponent(handle)}`).then(async r=>{const j=await r.json() as UserAnalysis&{error?:string};if(!r.ok)throw new Error(j.error);setItems(j.upsolves)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[handle]);
  function update(key:string,status:Status){const next={...statuses,[key]:status};setStatuses(next);localStorage.setItem(`cpulse-upsolve-${handle.toLowerCase()}`,JSON.stringify(next))}
  const visible=useMemo(()=>items.filter(i=>filter==="all"||(statuses[i.key]??"planned")===filter),[items,statuses,filter]);
  return <main className="mx-auto min-h-[80vh] max-w-6xl px-5 py-16"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-[#b7f34a]"><Target size={14}/>Recovery queue</div><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">{handle}&apos;s upsolve list</h1><p className="mt-3 text-sm text-zinc-500">Attempted, not yet accepted. Status changes are saved on this device.</p></div><div className="flex rounded-lg border border-white/8 bg-white/3 p-1">{(["planned","solved","skipped","all"] as const).map(value=><button key={value} onClick={()=>setFilter(value)} className={`rounded-md px-3 py-1.5 text-xs capitalize ${filter===value?"bg-white text-black":"text-zinc-500 hover:text-white"}`}>{value}</button>)}</div></div>{loading&&<div className="grid h-72 place-items-center"><LoaderCircle className="animate-spin text-[#b7f34a]"/></div>}{error&&<Card className="mt-8"><Empty>{error}</Empty></Card>}{!loading&&!error&&<Card className="mt-8 overflow-hidden">{visible.length?<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="text-zinc-600"><tr><th className="px-5 py-4 font-medium">Problem</th><th className="px-3 py-4 font-medium">Rating</th><th className="px-3 py-4 font-medium">Tags</th><th className="px-3 py-4 font-medium">Attempts</th><th className="px-3 py-4 font-medium">Last tried</th><th className="px-5 py-4 text-right font-medium">Status</th></tr></thead><tbody>{visible.map(item=><tr key={item.key} className="border-t border-white/7"><td className="px-5 py-4"><a href={item.url} target="_blank" rel="noreferrer" className="flex items-center gap-2 font-medium text-zinc-200 hover:text-[#b7f34a]">{item.index}. {item.name}<ExternalLink size={12}/></a></td><td className="px-3 py-4 text-zinc-400">{item.rating??"—"}</td><td className="max-w-72 px-3 py-4"><div className="flex gap-1 overflow-hidden">{item.tags.slice(0,3).map(tag=><Badge key={tag}>{tag}</Badge>)}</div></td><td className="px-3 py-4 text-red-400">{item.wrongAttempts}</td><td className="px-3 py-4 text-zinc-500">{formatRelativeTime(item.lastAttempted)}</td><td className="px-5 py-4 text-right"><select aria-label={`Status for ${item.name}`} value={statuses[item.key]??"planned"} onChange={e=>update(item.key,e.target.value as Status)} className="rounded-md border border-white/10 bg-[#11151a] px-2 py-1.5 capitalize text-zinc-300 outline-none"><option value="planned">Planned</option><option value="solved">Solved</option><option value="skipped">Skipped</option></select></td></tr>)}</tbody></table></div>:<Empty>No problems in this view. A suspiciously tidy queue.</Empty>}</Card>}</main>}
