"use client";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { RatingBucket, RatingChange, TagStat } from "@/types/codeforces";

const tooltipStyle = { background: "#11151a", border: "1px solid #2a2f37", borderRadius: 10, fontSize: 12 };
export function RatingChart({ data }: { data: RatingChange[] }) {
  const chart = data.map((item) => ({ ...item, date: new Date(item.ratingUpdateTimeSeconds * 1000).toLocaleDateString("en", { month: "short", year: "2-digit" }), change: item.newRating - item.oldRating }));
  return <ResponsiveContainer width="100%" height={270}><LineChart data={chart} margin={{ top: 15, right: 12, bottom: 5, left: -18 }}><CartesianGrid stroke="#20242b" vertical={false}/><XAxis dataKey="date" stroke="#666b75" fontSize={10} tickLine={false} axisLine={false} minTickGap={40}/><YAxis stroke="#666b75" fontSize={10} tickLine={false} axisLine={false} domain={["dataMin - 100", "dataMax + 100"]}/><Tooltip contentStyle={tooltipStyle} labelStyle={{color:"#90949e"}} formatter={(value, name, props) => name === "newRating" ? [value, `${props.payload.contestName} (${props.payload.change > 0 ? "+" : ""}${props.payload.change})`] : [value, name]}/><Line type="monotone" dataKey="newRating" stroke="#b7f34a" strokeWidth={2.2} dot={false} activeDot={{ r: 4, fill: "#b7f34a", stroke: "#080a0d", strokeWidth: 2 }}/></LineChart></ResponsiveContainer>;
}
export function DifficultyChart({ data }: { data: RatingBucket[] }) { return <ResponsiveContainer width="100%" height={230}><BarChart data={data} margin={{top:10,right:5,left:-26,bottom:0}}><CartesianGrid stroke="#20242b" vertical={false}/><XAxis dataKey="range" stroke="#666b75" fontSize={9} tickLine={false} axisLine={false}/><YAxis allowDecimals={false} stroke="#666b75" fontSize={10} tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle} cursor={{fill:"#ffffff05"}}/><Bar dataKey="count" fill="#b7f34a" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer> }
export function TagsChart({ data }: { data: TagStat[] }) { const chart = data.slice(0, 8).reverse(); return <ResponsiveContainer width="100%" height={260}><BarChart layout="vertical" data={chart} margin={{top:5,right:12,left:12,bottom:0}}><XAxis type="number" hide/><YAxis dataKey="tag" type="category" stroke="#8d929c" fontSize={10} tickLine={false} axisLine={false} width={86}/><Tooltip contentStyle={tooltipStyle} cursor={{fill:"#ffffff05"}}/><Bar dataKey="solved" fill="#83b937" radius={[0,4,4,0]}/><Bar dataKey="wrongAttempts" fill="#343a43" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer> }
export function ComparisonChart({ a, b, names }: { a: RatingChange[]; b: RatingChange[]; names: [string,string] }) { const toData = (items: RatingChange[]) => items.map((r, i) => ({i, rating:r.newRating})); const length = Math.max(a.length,b.length); const data=Array.from({length},(_,i)=>({i:i+1,a:toData(a)[i]?.rating,b:toData(b)[i]?.rating})); return <ResponsiveContainer width="100%" height={300}><LineChart data={data} margin={{top:15,right:15,left:-15,bottom:0}}><CartesianGrid stroke="#20242b" vertical={false}/><XAxis dataKey="i" stroke="#666b75" fontSize={10} tickLine={false} axisLine={false}/><YAxis stroke="#666b75" fontSize={10} tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle}/><Line dataKey="a" name={names[0]} stroke="#b7f34a" dot={false} strokeWidth={2}/><Line dataKey="b" name={names[1]} stroke="#8b5cf6" dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer> }
