"use client";
import { useEffect, useState } from "react";
import { Bell, Bookmark, BookmarkCheck, CalendarClock, ExternalLink, LoaderCircle } from "lucide-react";
import type { CFContest } from "@/types/codeforces";
import { Badge, Card, Empty } from "@/components/ui";
import { formatDuration } from "@/lib/utils";

function countdown(epoch?:number){if(!epoch)return "TBA";const diff=epoch*1000-Date.now();if(diff<=0)return "Starting";const d=Math.floor(diff/86400000),h=Math.floor(diff%86400000/3600000),m=Math.floor(diff%3600000/60000);return d?`${d}d ${h}h`:`${h}h ${m}m`}
export default function ContestsPage(){const [contests,setContests]=useState<CFContest[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [saved,setSaved]=useState<number[]>([]);const [,tick]=useState(0);
  useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem("cpulse-contests")??"[]");queueMicrotask(()=>setSaved(stored))}catch{};fetch("/api/codeforces/contests").then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setContests(j)}).catch(e=>setError(e.message)).finally(()=>setLoading(false));const timer=setInterval(()=>tick(n=>n+1),60000);return()=>clearInterval(timer)},[]);
  function toggle(id:number){const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);localStorage.setItem("cpulse-contests",JSON.stringify(next))}
  return <main className="mx-auto min-h-[80vh] max-w-5xl px-5 py-16"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-[#b7f34a]"><CalendarClock size={14}/>Contest radar</div><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Upcoming Codeforces rounds</h1><p className="mt-3 max-w-2xl text-sm text-zinc-500">Keep the next start time visible. Bookmarks stay on this device—simple on purpose.</p></div><Badge>{saved.length} bookmarked</Badge></div><div className="mt-9 space-y-3">{loading&&<div className="grid h-56 place-items-center"><LoaderCircle className="animate-spin text-[#b7f34a]"/></div>}{error&&<Card><Empty>{error}</Empty></Card>}{!loading&&!error&&!contests.length&&<Card><Empty>No upcoming contests announced yet.</Empty></Card>}{contests.map((contest,i)=><Card key={contest.id} className="group flex flex-col gap-4 p-5 transition hover:border-white/20 sm:flex-row sm:items-center"><div className="grid size-12 shrink-0 place-items-center rounded-xl border border-white/8 bg-white/3 text-sm font-semibold text-zinc-500">{String(i+1).padStart(2,"0")}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="truncate text-sm font-medium text-zinc-200">{contest.name}</h2><Badge>{contest.type}</Badge></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-zinc-600"><span>{contest.startTimeSeconds?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(contest.startTimeSeconds*1000):"Time TBA"}</span><span>{formatDuration(contest.durationSeconds)}</span></div></div><div className="sm:text-right"><p className="font-mono text-lg font-semibold text-[#b7f34a]">{countdown(contest.startTimeSeconds)}</p><p className="text-[10px] uppercase tracking-wider text-zinc-600">until start</p></div><div className="flex gap-2"><button aria-label="Bookmark contest" onClick={()=>toggle(contest.id)} className="grid size-9 place-items-center rounded-lg border border-white/9 hover:bg-white/5">{saved.includes(contest.id)?<BookmarkCheck size={16} className="text-[#b7f34a]"/>:<Bookmark size={16} className="text-zinc-500"/>}</button><a aria-label="Open contest" href={`https://codeforces.com/contest/${contest.id}`} target="_blank" rel="noreferrer" className="grid size-9 place-items-center rounded-lg border border-white/9 hover:bg-white/5"><ExternalLink size={15} className="text-zinc-500"/></a></div></Card>)}</div><div className="mt-8 flex items-center gap-2 text-xs text-zinc-600"><Bell size={13}/>Contest times are shown in your local timezone.</div></main>}
